Added some changes, please review and give suggestions
marsiitr/Bipedal-Robot pull request #1
Opened 2020-07-28 07:58 UTC by Aayush-765

2020-07-28 08:35 UTC, SanjeevKrishnan requested changes
@Aayush-765 Lot of changes are required!
1. Images and Videos folder is compulsory. Add it with two sub-folders, "Images" and "Videos" which should contain project related images(except CAD images) and project-related videos(like animations or code stimulation videos).
2. Report is missing inside Poster and Report. A Project Report in pdf format is a must.
3. Poster is not up to the mark. Make sure that you mention "Models and Robotics Section", "Srishti 2020" in your poster. Also, other unnecessary elements should not be present in poster.(Check bottom left corner of your poster).
4. src folder is missing. You should make one folder named "src" and have project related code files(like arduino codes, python codes) inside.
5. README.md is blank. Update it as mentioned in the guideline.

2020-07-28 10:32 UTC, Aayush-765 commented
Actually  it was not complete earlier, I thought that we could add it one
by one.
But actually there is no working video available, and no one has the bot
right now, we have some images which were clicked earlier.

On Tue, 28 Jul 2020, 14:06 Sanjeev Krishnan R., <notifications@github.com>
wrote:

> *@SanjeevKrishnan* requested changes on this pull request.
>
> @Aayush-765 <https://github.com/Aayush-765> Lot of changes are required!
>
>    1. Images and Videos folder is compulsory. Add it with two
>    sub-folders, "Images" and "Videos" which should contain project related
>    images(except CAD images) and project-related videos(like animations or
>    code stimulation videos).
>    2. Report is missing inside Poster and Report. A Project Report in pdf
>    format is a must.
>    3. Poster is not up to the mark. Make sure that you mention "Models
>    and Robotics Section", "Srishti 2020" in your poster. Also, other
>    unnecessary elements should not be present in poster.(Check bottom left
>    corner of your poster).
>    4. src folder is missing. You should make one folder named "src" and
>    have project related code files(like arduino codes, python codes) inside.
>    5. README.md is blank. Update it as mentioned in the guideline.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/marsiitr/Bipedal-Robot/pull/1#pullrequestreview-456419146>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQF3M7FBKP6DBITLTA57PDR52EXDANCNFSM4PKHTFHQ>
> .
>

2020-07-28 10:52 UTC, SanjeevKrishnan commented
> Actually it was not complete earlier, I thought that we could add it one by one. But actually there is no working video available, and no one has the bot right now, we have some images which were clicked earlier.
> […](#)


@Shubhanshu07 Please clarify regarding video!

2020-07-28 13:34 UTC, SanjeevKrishnan commented
> Actually it was not complete earlier, I thought that we could add it one by one. But actually there is no working video available, and no one has the bot right now, we have some images which were clicked earlier.
> […](#)
@Aayush-765 Try to make some stimulation videos as it will be advantageous to your repo. If it is genuinely not possible to make one then you can skip adding Videos.

2020-07-28 13:36 UTC, Shubhanshu07 commented
@Aayush-765
1. Write content of readme normal not in italics.
2. Do not use any internet photo.
3. Write team members and mentors as ordered list not  unorders list.
4. Add solid works jped in readme also.
5. For video you can upload bot recognition video using shapes and all.
6. Flow chart is missing.

2020-07-28 15:30 UTC, Aayush-765 commented
Sir actually I am unable to create a new pull request, since I made one
earlier. Could you help me out with this?

On Tue, 28 Jul 2020, 19:07 Shubhs, <notifications@github.com> wrote:

> @Aayush-765 <https://github.com/Aayush-765>
>
>    1. Write content of readme normal not in italics.
>    2. Do not use any internet photo.
>    3. Write team members and mentors as ordered list not unorders list.
>    4. Add solid works jped in readme also.
>    5. For video you can upload bot recognition video using shapes and all.
>    6. Flow chart is missing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/marsiitr/Bipedal-Robot/pull/1#issuecomment-665044755>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQF3M6IRXYSO7FNSU7J2DLR53H73ANCNFSM4PKHTFHQ>
> .
>

2020-07-28 19:01 UTC, SanjeevKrishnan requested changes
@Aayush-765 Changes Required!
1. Move Images out of Images and Video folders. As there are no videos, "Images and Videos" is not necessary.
2. Report has to be realigned. Dont break team members into two pages.
3. Also include, "Models and Robotics Section" along with its logo in Report.
4. Poster and Report need not be inside subfolders.
5. Justify text in README.md using HTML tags.

2020-07-28 19:12 UTC, SanjeevKrishnan commented
@Aayush-765 Also, you don't have to create a new pull request every time. All your changes get updated in this pull request itself. Just leave a comment here mentioning that "Changes have been made" once your repo is ready!

2020-07-28 20:09 UTC, Aayush-765 commented
Changes have been made.

2020-07-29 05:42 UTC, SanjeevKrishnan requested changes
@Aayush-765 Text in REAME.md and Report is yet to be justified.
You can use `<p align="justify">content<\p> `to justify, where content is the text you want to justify.

2020-07-29 06:28 UTC, SanjeevKrishnan approved these changes
@Aayush-765 All requirements are met!
@Shubhanshu07 I suggest for merge!

2020-07-29 06:33 UTC, Shubhanshu07 commented
@Aayush-765 
Remove  unnecessary space between the point in README

2020-07-29 06:36 UTC, Shubhanshu07 commented on README.md
> +## Applications
Remove <P> tag from here

2020-07-29 06:40 UTC, Aayush-765 commented
Sir please give me 5 mins

On Wed, 29 Jul 2020, 12:06 Shubhanshu Agarwal, <notifications@github.com>
wrote:

> *@Shubhanshu07* commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Bipedal-Robot/pull/1#discussion_r462070209>:
>
> > +   																																	
> +4. <p align="justify">Microcontroller
> +
> +   Arduino UNO R3 is used as the microcontroller which can operate six Servo motors at a time, enabling various types of motion such as forward, backward etc.</p>
> +
> +## Cost Structure
> +
> +| Materials  | Cost(INR) |
> +| ------------- | ------------- |
> +| 6 DC Servo Motors | 3000 |
> +| Arduino UNO R3  |400 |
> +|  11.1 Li-Po Battery  | 1800 |
> +| Miscellaneous | 300 |
> +| Total | 5500 |
> +
> +## Applications
>
> Remove
>
> tag from here
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/marsiitr/Bipedal-Robot/pull/1#pullrequestreview-457231758>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQF3M3FA4WIUVFJE7L26B3R567O7ANCNFSM4PKHTFHQ>
> .
>

2020-07-29 06:48 UTC, Aayush-765 commented
sir please review now

2020-07-29 06:56 UTC, Shubhanshu07 commented
@Aayush-765 
PR looks good to me. 
Closing and merging the PR

2020-07-29 06:56 UTC, merged

2020-07-29 06:59 UTC, Aayush-765 commented
thank you sir